// macOS golden-image ops contract tests.
//
// Covers the two artifacts build-golden-image.sh and Task 1.3 depend on:
// the pinned CLI manifest (ops/macos-vm/cli-manifest.txt, generated by
// generate-cli-manifest.sh) and the guest credential probe
// (ops/macos-vm/probe-guest-credentials.sh).
//
// Three things here cannot be checked by reading the scripts:
//
//   1. The manifest has to satisfy the build script's OWN validator, not a
//      restatement of it. So the validator is extracted from
//      build-golden-image.sh and run against the committed manifest — a
//      loosened rule there can never drift away from what is tested here.
//
//   2. The probe's guest half runs under whatever /bin/bash the guest has, and
//      macOS still ships bash 3.2.57. A construct that works in the 5.x on the
//      developer's PATH can fail there, so the generated guest script is
//      syntax-checked and its classifier is executed under /bin/bash.
//
//   3. The classifier must read output, not exit status. Measured 2026-08-14
//      against the pinned CLIs: `cursor-agent status` and `opencode auth list`
//      both exit 0 while logged out. Scoring those by exit code reports a
//      logged-out CLI as ready, which is the wrong "yes" the whole credential
//      table exists to prevent — so those two fixtures are asserted directly.
//
// Nothing here talks to Parallels or boots a VM: the probe is rendered, not
// dispatched.

import { deepStrictEqual, ok, strictEqual } from "node:assert";
import { spawnSync } from "node:child_process";
import {
	accessSync,
	constants,
	existsSync,
	mkdtempSync,
	readFileSync,
	writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";
import { VM_TAR_PROVISIONABLE_PROVIDERS } from "../src/switchyard/lifecycle/index.mjs";
import { createQueueBackend } from "../src/switchyard/runner/index.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, "..");
const VM_OPS = resolve(PKG_ROOT, "ops/macos-vm");

const BUILD = resolve(VM_OPS, "build-golden-image.sh");
const GENERATOR = resolve(VM_OPS, "generate-cli-manifest.sh");
const PROBE = resolve(VM_OPS, "probe-guest-credentials.sh");
const MANIFEST = resolve(VM_OPS, "cli-manifest.txt");
const TAR_MANIFEST = resolve(VM_OPS, "tar-provision-manifest.json");
const DOCKERFILE = resolve(PKG_ROOT, "docker/Dockerfile");

const IS_DARWIN = process.platform === "darwin";
const notDarwin = { skip: IS_DARWIN ? false : "macOS-only ops lane" };

// The build script requires exactly these six, and install_guest_tools asserts
// all six are on PATH afterwards.
const REQUIRED_PROVIDERS = [
	"claude",
	"codex",
	"agy",
	"cursor-agent",
	"copilot",
	"opencode",
];

// Where each provider's install ref must also appear. docker/Dockerfile is the
// source of record for what switchyard installs; a ref that changes there and
// not here would build a macOS image carrying a different CLI than the
// container lane, which no other test would notice.
const EXPECTED_REFS = {
	claude: "https://claude.ai/install.sh",
	codex: "https://chatgpt.com/codex/install.sh",
	agy: "https://antigravity.google/cli/install.sh",
	"cursor-agent": "https://cursor.com/install",
	copilot: "@github/copilot",
	opencode: "opencode-ai",
};

const readManifestRows = () =>
	readFileSync(MANIFEST, "utf8")
		.split("\n")
		.map((line) => line.trim())
		.filter((line) => line.length > 0 && !line.startsWith("#"))
		.map((line) => {
			const [provider, kind, ref, detail, hash, ...rest] = line.split("|");
			return { provider, kind, ref, detail, hash, rest, line };
		});

// Pulls a top-level `name() { ... }` block out of a shell script by matching
// the closing brace in column 1. Every function in these scripts is written
// that way, which is what makes the extraction safe.
const extractShellFunction = (body, name) => {
	const start = body.indexOf(`${name}() {`);
	ok(start !== -1, `no ${name}() in script`);
	const end = body.indexOf("\n}\n", start);
	ok(end !== -1, `unterminated ${name}()`);
	return body.slice(start, end + 3);
};

const scratch = () => mkdtempSync(join(tmpdir(), "switchyard-vm-ops-"));

// Renders the guest-side script the probe would feed to `prlctl exec`, without
// needing Parallels: the one prlctl call is swapped for cat and the running-VM
// precondition is dropped.
const renderGuestScript = (dir) => {
	const rendered = readFileSync(PROBE, "utf8")
		.replace('  prlctl exec "$VM_NAME" /bin/bash -s <<EOF', "  cat <<EOF")
		.replace(/^ {2}require_host_tools$/m, "  true");
	ok(rendered.includes("cat <<EOF"), "probe's prlctl exec call moved");
	// Prose mentions prlctl exec repeatedly; only a command position matters.
	ok(
		!/^\s*prlctl exec\b/m.test(rendered),
		"probe has a second prlctl exec call",
	);
	const harness = join(dir, "render.sh");
	writeFileSync(harness, rendered);
	const run = spawnSync(
		"/bin/bash",
		[harness, "--vm", "probe-vm", "--phase", "baseline"],
		{
			encoding: "utf8",
		},
	);
	strictEqual(run.status, 0, `render failed: ${run.stderr}`);
	return run.stdout;
};

describe("macOS golden-image ops artifacts", () => {
	it("ships the generator, the probe, and a generated manifest", () => {
		for (const script of [BUILD, GENERATOR, PROBE]) {
			ok(existsSync(script), `missing: ${script}`);
			accessSync(script, constants.X_OK);
		}
		ok(existsSync(MANIFEST), `missing: ${MANIFEST}`);
	});

	it("every ops script passes `bash -n`", () => {
		for (const script of [BUILD, GENERATOR, PROBE]) {
			const r = spawnSync("bash", ["-n", script], { encoding: "utf8" });
			strictEqual(r.status, 0, `bash -n failed for ${script}: ${r.stderr}`);
		}
	});

	// Regression, measured in switchyard-check-2 on 2026-08-14. The C-3 block
	// rules carry no direction, so they also drop packets addressed TO
	// 10.0.0.0/8 -- which includes the guest's own shared-network address, which
	// includes the DHCP OFFER. A clone with a fresh MAC therefore never
	// completed a lease, fell back to 169.254, and had no network at all: every
	// provider auth check that needs the network read as unauthenticated. The
	// build VM cannot catch this, because it already holds a lease taken before
	// pf was loaded and renewals are stateful unicast the port-67 rule passes.
	// pf takes the first quick match, so presence is not enough -- order is the
	// property.
	it("passes DHCP in both directions above the C-3 blocks", () => {
		const body = readFileSync(BUILD, "utf8");
		const start = body.indexOf('anchor "switchyard-transfer/*"');
		ok(start !== -1, "C-3 anchor rules moved");
		const end = body.indexOf("\nPFEOF", start);
		ok(end !== -1, "unterminated C-3 anchor heredoc");
		const rules = body
			.slice(start, end)
			.split("\n")
			.filter((line) => !line.trimStart().startsWith("#"));

		const dhcpOut = rules.findIndex((line) =>
			/^pass\s+out quick on en0 proto udp from any port 68 to any port 67$/.test(
				line.replace(/\s+/g, " ").trim(),
			),
		);
		const dhcpIn = rules.findIndex((line) =>
			/^pass\s+in quick on en0 proto udp from any port 67 to any port 68$/.test(
				line.replace(/\s+/g, " ").trim(),
			),
		);
		const firstBlock = rules.findIndex((line) =>
			line.startsWith("block drop quick on en0"),
		);

		ok(dhcpOut !== -1, "no outbound DHCP pass in the C-3 anchor");
		ok(dhcpIn !== -1, "no inbound DHCP pass in the C-3 anchor");
		ok(firstBlock !== -1, "C-3 anchor lost its RFC1918 blocks");
		ok(
			dhcpOut < firstBlock && dhcpIn < firstBlock,
			"a DHCP pass below the blocks never matches: a fresh-MAC clone gets no lease",
		);
	});
});

describe("the pinned CLI manifest", () => {
	it("passes build-golden-image.sh's own validator", notDarwin, () => {
		const body = readFileSync(BUILD, "utf8");
		const dir = scratch();
		const harness = join(dir, "validate.sh");
		// log() and fail() are what the validator reports through; take them
		// from the same file rather than restating them.
		writeFileSync(
			harness,
			[
				"#!/bin/bash",
				"set -Eeuo pipefail",
				'readonly SCRIPT_NAME="validator-harness"',
				extractShellFunction(body, "log"),
				extractShellFunction(body, "fail"),
				extractShellFunction(body, "validate_cli_manifest"),
				`CLI_MANIFEST=${JSON.stringify(MANIFEST)}`,
				"validate_cli_manifest",
				'printf "MANIFEST OK\\n"',
			].join("\n"),
		);
		const r = spawnSync("bash", [harness], { encoding: "utf8" });
		strictEqual(r.status, 0, `validator rejected the manifest: ${r.stderr}`);
		ok(r.stdout.includes("MANIFEST OK"));
	});

	it("covers exactly the six providers the build asserts on PATH", () => {
		const rows = readManifestRows();
		strictEqual(rows.length, REQUIRED_PROVIDERS.length);
		const providers = rows.map((row) => row.provider).sort();
		strictEqual(providers.join(","), [...REQUIRED_PROVIDERS].sort().join(","));
	});

	it("pins each ref to the one docker/Dockerfile installs", () => {
		const dockerfile = readFileSync(DOCKERFILE, "utf8");
		for (const row of readManifestRows()) {
			strictEqual(
				row.ref,
				EXPECTED_REFS[row.provider],
				`manifest ref drifted for ${row.provider}`,
			);
			ok(
				dockerfile.includes(row.ref),
				`docker/Dockerfile no longer installs ${row.provider} from ${row.ref}`,
			);
		}
	});

	it("carries a full sha256 on every row and a version on every npm row", () => {
		for (const row of readManifestRows()) {
			strictEqual(row.rest.length, 0, `trailing field: ${row.line}`);
			ok(/^[0-9a-f]{64}$/.test(row.hash), `not a sha256: ${row.line}`);
			if (row.kind === "npm") {
				// The npm rows are the only version-pinned ones; the script refs
				// are unversioned endpoints held in place by the hash alone.
				ok(
					/^[0-9][0-9A-Za-z.+_-]*$/.test(row.detail),
					`bad version: ${row.line}`,
				);
			} else {
				strictEqual(row.kind, "script");
				ok(
					row.detail === "bash" || row.detail === "sh",
					`bad shell: ${row.line}`,
				);
				ok(
					row.ref.startsWith("https://"),
					`installer must be HTTPS: ${row.line}`,
				);
			}
		}
	});

	it("is generated, and says so, so no one hand-edits a hash", () => {
		const header = readFileSync(MANIFEST, "utf8");
		ok(/GENERATED BY generate-cli-manifest\.sh/.test(header));
		ok(/Do not hand-edit a hash/.test(header));
	});

	it("has a generator that refuses an npm row the registry does not confirm", () => {
		const body = readFileSync(GENERATOR, "utf8");
		// The npm rows are the only ones with an independent witness; losing
		// that check would silently downgrade them to "whatever this host had".
		ok(body.includes("dist.tarball"), "generator no longer reads dist.tarball");
		ok(
			/\[\[ "\$packed_hash" == "\$registry_hash" \]\] \|\|/.test(body),
			"generator no longer compares the packed and registry tarballs",
		);
	});
});

describe("the guest credential probe", () => {
	it(
		"renders a guest script that is syntax-clean under bash",
		notDarwin,
		() => {
			const dir = scratch();
			const guest = join(dir, "guest.sh");
			writeFileSync(guest, renderGuestScript(dir));
			const r = spawnSync("/bin/bash", ["-n", guest], { encoding: "utf8" });
			strictEqual(r.status, 0, `guest script is not valid bash: ${r.stderr}`);
		},
	);

	it(
		"routes every check through the provider's Aqua session",
		notDarwin,
		() => {
			const guest = renderGuestScript(scratch());
			// prlctl exec lands as root in the System domain; the CLIs live in the
			// auto-login account's Aqua session and the two see different Keychains.
			ok(
				/\/bin\/launchctl asuser "\$uid" \/usr\/bin\/sudo -iu "\$provider_user"/.test(
					guest,
				),
				"probe no longer enters the Aqua session the way install_guest_tools does",
			);
			ok(
				/launchctl managername/.test(guest),
				"probe no longer reports which domain it measured",
			);
		},
	);

	it("never asks the Keychain for secret data", () => {
		const body = readFileSync(PROBE, "utf8");
		const dumps = body.match(/security dump-keychain[^\n|]*/g) ?? [];
		ok(dumps.length > 0, "probe no longer enumerates the Keychain");
		for (const call of dumps) {
			ok(!/\s-d\b/.test(call), `dump-keychain must never use -d: ${call}`);
		}
		ok(
			!/security\s+find-generic-password[^\n]*-w/.test(body),
			"probe must not print a password",
		);
	});

	it(
		"scores the measured CLI outputs by output, not exit status",
		notDarwin,
		() => {
			const guest = renderGuestScript(scratch());
			const dir = scratch();
			const harness = join(dir, "classify.sh");
			writeFileSync(
				harness,
				[
					"set -uo pipefail",
					extractShellFunction(guest, "bounded"),
					extractShellFunction(guest, "classify"),
					// awk, not `head -1`: head would close the pipe early and
					// pipefail would surface classify's SIGPIPE as a harness failure.
					"verdict() {",
					'  classify "$@" | awk -F"\\t" \'NR==1 {print $2}\'',
					"}",
				].join("\n"),
			);

			// provider, unauth regex, auth rule, fixture stdout, fixture exit, want.
			// Every fixture is a real output captured from the pinned CLIs on
			// 2026-08-14 in a credential-free container.
			const cases = [
				[
					"claude",
					'"loggedIn": false',
					'"loggedIn": true',
					'{\n  "loggedIn": false\n}',
					1,
					"unauthenticated",
				],
				[
					"claude",
					'"loggedIn": false',
					'"loggedIn": true',
					'{\n  "loggedIn": true\n}',
					0,
					"authenticated",
				],
				[
					"codex",
					"Not logged in",
					"Logged in",
					"Not logged in",
					1,
					"unauthenticated",
				],
				[
					"agy",
					"Please sign in|authentication required",
					"gemini-",
					"Error: Please sign in to view available models.",
					1,
					"unauthenticated",
				],
				// agy words its refusal differently in the VM than in the container.
				// Measured in switchyard-check-2 on 2026-08-14; the container fixture
				// above is the same day. Both must score unauthenticated.
				[
					"agy",
					"Please sign in|authentication required",
					"gemini-",
					"Error: authentication required. Run 'agy' to log in, then retry.",
					1,
					"unauthenticated",
				],
				[
					"agy",
					"Please sign in|authentication required",
					"gemini-",
					"gemini-3.7-flash-medium",
					0,
					"authenticated",
				],
				// The two that exit 0 while logged out.
				[
					"cursor-agent",
					"Not logged in",
					"Logged in|Email|Account",
					"Not logged in",
					0,
					"unauthenticated",
				],
				[
					"opencode",
					"0 credentials",
					"[1-9][0-9]* credentials",
					"0 credentials",
					0,
					"unauthenticated",
				],
				[
					"opencode",
					"0 credentials",
					"[1-9][0-9]* credentials",
					"3 credentials",
					0,
					"authenticated",
				],
				[
					"copilot",
					"No authentication information found",
					"exit0",
					"Error: No authentication information found.",
					1,
					"unauthenticated",
				],
				[
					"copilot",
					"No authentication information found",
					"exit0",
					"ok",
					0,
					"authenticated",
				],
				// A transport failure is neither, and must not be scored as a pass.
				[
					"copilot",
					"No authentication information found",
					"exit0",
					"fetch failed",
					1,
					"indeterminate",
				],
			];

			for (const [provider, unauth, rule, output, status, want] of cases) {
				const fixture = join(dir, "fixture.sh");
				writeFileSync(
					fixture,
					`printf '%s\\n' ${JSON.stringify(output)}\nexit ${status}\n`,
				);
				const r = spawnSync(
					"/bin/bash",
					[
						"-c",
						`. ${JSON.stringify(harness)}; verdict "$@"`,
						"harness",
						provider,
						unauth,
						rule,
						"/bin/sh",
						fixture,
					],
					{ encoding: "utf8" },
				);
				strictEqual(r.status, 0, `classify harness failed: ${r.stderr}`);
				strictEqual(
					r.stdout.trim(),
					want,
					`${provider} with output ${JSON.stringify(output)} exit ${status}`,
				);
			}
		},
	);

	it("bounds a hung provider check without coreutils", notDarwin, () => {
		const guest = renderGuestScript(scratch());
		const dir = scratch();
		const harness = join(dir, "bounded.sh");
		writeFileSync(
			harness,
			`set -uo pipefail\n${extractShellFunction(guest, "bounded")}\n`,
		);
		const started = Date.now();
		const r = spawnSync(
			"/bin/bash",
			["-c", `. ${JSON.stringify(harness)}; bounded 1 /bin/sleep 30`],
			{ encoding: "utf8" },
		);
		const elapsed = Date.now() - started;
		ok(r.status !== 0, "a hung check must not report success");
		ok(elapsed < 10_000, `alarm did not fire: ${elapsed}ms`);
	});

	// Regression, found on the first real guest run (2026-08-14): the probe is
	// itself delivered to `bash -s` on stdin, so a provider that reads stdin --
	// agy does, when it decides to prompt for a login -- swallows the remainder
	// of the script. The baseline run ended silently after agy and never ran
	// cursor-agent, copilot, or opencode. Nothing failed; three rows just
	// disappeared, which is the worst shape a credential probe can fail in.
	it(
		"does not let a provider check eat the rest of the script",
		notDarwin,
		() => {
			const guest = renderGuestScript(scratch());
			const dir = scratch();
			const harness = join(dir, "stdin.sh");
			writeFileSync(
				harness,
				[
					"set -uo pipefail",
					extractShellFunction(guest, "bounded"),
					extractShellFunction(guest, "classify"),
					// /bin/cat is the minimal stand-in for a stdin-reading provider.
					"classify greedy no-such-string exit0 /bin/cat >/dev/null 2>&1",
					'printf "SURVIVED\\n"',
				].join("\n"),
			);
			const r = spawnSync("/bin/bash", ["-s"], {
				encoding: "utf8",
				input: readFileSync(harness, "utf8"),
			});
			strictEqual(
				r.stdout.trim(),
				"SURVIVED",
				"a stdin-reading provider consumed the script tail",
			);
		},
	);
});

// The recorded measurement and the code that acts on it are two different
// files, and they fail in opposite directions when they disagree. A manifest
// that admits a provider the credential table cannot carry produces the
// expensive failure the preflight exists to prevent: VM up, slot held, task
// dead at exec. A manifest that omits one the table can carry silently narrows
// the routable set with no error anywhere.
describe("the tar-provision manifest", () => {
	const manifest = JSON.parse(readFileSync(TAR_MANIFEST, "utf8"));

	it("is what the macOS preflight loads with no env override", () => {
		const previous = process.env.SWITCHYARD_MACOS_TAR_PROVISION_MANIFEST;
		// Deleted, not emptied: the shipped default is only reached when the
		// variable is absent, and an empty string would resolve to cwd.
		delete process.env.SWITCHYARD_MACOS_TAR_PROVISION_MANIFEST;
		try {
			const backend = createQueueBackend({
				platform: "macos",
				dependencies: {
					preflightReadSnapshot: () => ({
						snapshot: {
							schema_version: 2,
							updated_at: new Date().toISOString(),
							providers: [
								{
									name: "codex",
									ok: true,
									windows: [{ percent_left: 80, pace_delta: 1 }],
								},
							],
						},
						snapshotStatus: "fresh",
						snapshotMtime: 1,
						snapshotAgeMsAtRoute: 0,
					}),
				},
			});
			// A pending task is required: with an empty queue the preflight
			// returns `no_non_terminal_tasks` before it ever consults the
			// registry, and this assertion would hold with no manifest at all.
			// Until 2026-08-14 nothing shipped a manifest, so this call threw
			// `tar_provisionability_unverified` and every provider was rejected.
			const result = backend.preflight({
				tasks: [{ status: "pending", requiredCapability: "high" }],
			});
			strictEqual(result.ok, true);
		} finally {
			if (previous !== undefined)
				process.env.SWITCHYARD_MACOS_TAR_PROVISION_MANIFEST = previous;
		}
	});

	it("admits exactly the providers the credential table can carry", () => {
		const admitted = Object.entries(manifest.providers)
			.filter(([, evidence]) => evidence.tarProvisionable === true)
			.map(([provider]) => provider);
		deepStrictEqual(admitted, [...VM_TAR_PROVISIONABLE_PROVIDERS]);
	});

	it("records every provider, including the measured no", () => {
		deepStrictEqual(
			Object.keys(manifest.providers).sort(),
			[...REQUIRED_PROVIDERS].sort(),
		);
		// cursor-agent is the reason this column is measured rather than
		// inferred: file-backed in shape, machine-bound in behavior.
		strictEqual(manifest.providers["cursor-agent"].tarProvisionable, false);
		for (const [provider, evidence] of Object.entries(manifest.providers)) {
			ok(evidence.check, `${provider} records no auth check`);
			ok(evidence.evidence, `${provider} records no evidence`);
			strictEqual(
				evidence.files.length > 0,
				evidence.tarProvisionable,
				`${provider} lists files inconsistently with its verdict`,
			);
		}
	});
});

describe("the macOS queue backend", () => {
	it("provisions credentials instead of returning null", () => {
		const provisioned = [];
		const read = [];
		const backend = createQueueBackend({
			platform: "macos",
			dependencies: {
				goldenImage: "{golden}",
				aquaUid: 503,
				providerUser: "switchyard",
				executionBackend: {
					provisionCredentials(workspaceId, options) {
						provisioned.push({ workspaceId, provider: options.provider });
						return { provider: options.provider, files: options.credentials };
					},
				},
				// The vault is a Docker container this test must not touch, and a
				// real read would pull live credential bytes into this process.
				readCredentialTar: (_agent, src) => {
					read.push(src);
					return Buffer.from(src);
				},
			},
		});
		const report = backend.provision("{vm-uuid}");
		// Until 2026-08-14 this was `() => null`: the guest booted with no
		// credentials at all and every provider failed authentication at exec.
		deepStrictEqual(
			provisioned.map((call) => call.provider),
			[...VM_TAR_PROVISIONABLE_PROVIDERS],
		);
		strictEqual(provisioned[0].workspaceId, "{vm-uuid}");
		strictEqual(report.provisioned, read.length);
		deepStrictEqual(report.skipped, []);
		// Every source is read out of the standing vault's root home, never off
		// the host filesystem.
		for (const src of read) ok(src.startsWith("/root/"));
	});

	it("reports a provider it could not seed rather than failing the queue", () => {
		const backend = createQueueBackend({
			platform: "macos",
			dependencies: {
				goldenImage: "{golden}",
				executionBackend: {
					provisionCredentials: (_workspaceId, options) => ({
						provider: options.provider,
						files: options.credentials,
					}),
				},
				readCredentialTar: (_agent, src) => {
					if (src.startsWith("/root/.copilot/"))
						throw new Error(
							"credential source is absent from the standing vault",
						);
					return Buffer.from(src);
				},
			},
		});
		const report = backend.provision("{vm-uuid}");
		deepStrictEqual(
			report.skipped.map((skip) => skip.provider),
			["copilot"],
		);
		// The other four still land: the VM lane seeds before routing, so one
		// never-logged-in provider must not leave the rest unauthenticated.
		strictEqual(report.provisioned, 5);
	});
});
