#!/bin/bash
# Update the pinned provider CLIs in an existing stopped Parallels VM, in place.
#
# Unlike build-golden-image.sh this never rebuilds the image, so provider logins
# stored in the guest survive. The host never receives or stores credentials.
# The install and version-check logic mirrors build-golden-image.sh's
# install_guest_tools and is driven by the same pinned manifest
# (ops/macos-vm/cli-manifest.txt, regenerated by generate-cli-manifest.sh).
#
# Sequence: require a stopped VM, take a rollback snapshot, start it, install
# every selected manifest row with its SHA-256 checked, fail closed unless each
# CLI's `--version` names exactly the pinned release, then stop the VM.
set -Eeuo pipefail
IFS=$'\n\t'

readonly SCRIPT_NAME="$(basename "$0")"
readonly PROVIDER_USER="switchyard"
readonly POLL_ATTEMPTS=30
readonly POLL_SECONDS=2
readonly TOOLS_EXEC_TIMEOUT_SECONDS=30
readonly UPDATE_EXEC_TIMEOUT_SECONDS=1800
readonly HEARTBEAT_SECONDS=30
readonly KNOWN_PROVIDERS=(claude codex agy cursor-agent copilot opencode vibe)

VM_NAME=""
CLI_MANIFEST=""
SNAPSHOT_NAME=""
NO_SNAPSHOT=0
ONLY=()
STARTED=0
SUBSET_MANIFEST=""

log() {
  printf '[%s] %s\n' "$SCRIPT_NAME" "$*" >&2
}

fail() {
  log "ERROR: $*"
  exit 1
}

usage() {
  cat >&2 <<'EOF'
Usage:
  update-guest-clis.sh --vm NAME --cli-manifest PATH [--only PROVIDER]...
                       [--snapshot-name NAME | --no-snapshot]

Updates the provider CLIs named by the manifest (all seven by default, or only
the repeatable --only PROVIDERs) inside the stopped VM, then stops it again.
A rollback snapshot is taken first unless --no-snapshot is given.
PROVIDER is one of: claude codex agy cursor-agent copilot opencode vibe.
EOF
}

require_value() {
  [[ $# -ge 2 && -n "$2" ]] || fail "missing value for $1"
}

validate_vm_name() {
  [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$ ]] || fail "unsafe VM name: $1"
}

validate_manifest_path() {
  [[ "$1" == /* ]] || fail "manifest path must be absolute: $1"
  [[ "$1" != *$'\n'* && "$1" != *$'\r'* ]] || fail "manifest path contains a line break"
  [[ "$1" != -* && -r "$1" && -f "$1" ]] || fail "manifest path is not a readable regular file: $1"
}

is_known_provider() {
  local candidate="$1" known
  for known in "${KNOWN_PROVIDERS[@]}"; do
    [[ "$candidate" == "$known" ]] && return 0
  done
  return 1
}

parse_args() {
  local seen_vm=0 seen_manifest=0
  while (($#)); do
    case "$1" in
      --vm)
        ((seen_vm == 0)) || fail "duplicate --vm"
        require_value "$@"
        VM_NAME="$2"
        seen_vm=1
        shift 2
        ;;
      --cli-manifest)
        ((seen_manifest == 0)) || fail "duplicate --cli-manifest"
        require_value "$@"
        CLI_MANIFEST="$2"
        seen_manifest=1
        shift 2
        ;;
      --only)
        require_value "$@"
        is_known_provider "$2" || fail "unknown provider for --only: $2"
        ONLY+=("$2")
        shift 2
        ;;
      --snapshot-name)
        require_value "$@"
        [[ "$2" =~ ^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$ ]] || fail "unsafe snapshot name: $2"
        SNAPSHOT_NAME="$2"
        shift 2
        ;;
      --no-snapshot)
        NO_SNAPSHOT=1
        shift
        ;;
      -h | --help)
        usage
        exit 0
        ;;
      *)
        usage
        fail "unknown argument: $1"
        ;;
    esac
  done
  ((seen_vm == 1)) || fail "--vm is required"
  ((seen_manifest == 1)) || fail "--cli-manifest is required"
  [[ -z "$SNAPSHOT_NAME" || $NO_SNAPSHOT -eq 0 ]] || fail "--snapshot-name and --no-snapshot conflict"
  validate_vm_name "$VM_NAME"
  validate_manifest_path "$CLI_MANIFEST"
}

# Validates every row and writes the rows selected by --only (or all rows) to
# SUBSET_MANIFEST. A provider named by --only that has no row is an error.
select_manifest_rows() {
  local line provider kind ref detail hash version extra selected only_match
  local seen=" "
  SUBSET_MANIFEST="$(mktemp "${TMPDIR:-/tmp}/switchyard-cli-subset.XXXXXX")"
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ -z "$line" || "$line" == \#* ]] && continue
    IFS='|' read -r provider kind ref detail hash version extra <<<"$line"
    [[ -n "$provider" && -n "$kind" && -n "$ref" && -n "$detail" && -n "$hash" && -n "$version" && -z "${extra:-}" ]] ||
      fail "malformed manifest row: $line"
    is_known_provider "$provider" || fail "unknown provider in manifest: $provider"
    [[ "$kind" =~ ^(script|npm|brew)$ ]] || fail "unsupported kind for $provider: $kind"
    [[ "$hash" =~ ^[0-9a-fA-F]{64}$ ]] || fail "$provider row must contain a 64-character SHA-256"
    [[ "$version" =~ ^[0-9][0-9A-Za-z.+_-]*$ ]] || fail "unsafe version for $provider: $version"
    seen+="$provider "
    selected=1
    if ((${#ONLY[@]})); then
      selected=0
      for only_match in "${ONLY[@]}"; do
        [[ "$only_match" == "$provider" ]] && selected=1
      done
    fi
    ((selected == 1)) && printf '%s\n' "$line" >>"$SUBSET_MANIFEST"
  done <"$CLI_MANIFEST"
  if ((${#ONLY[@]})); then
    for only_match in "${ONLY[@]}"; do
      [[ "$seen" == *" $only_match "* ]] || fail "manifest has no row for --only $only_match"
    done
  fi
  [[ -s "$SUBSET_MANIFEST" ]] || fail "no manifest rows selected"
}

require_host_tools() {
  local tool
  for tool in prlctl base64 shasum; do
    command -v "$tool" >/dev/null 2>&1 || fail "missing host tool: $tool"
  done
}

run_bounded() {
  local timeout_seconds="$1"
  shift
  local pid elapsed=0 grace=0

  "$@" <&0 &
  pid=$!
  while kill -0 "$pid" 2>/dev/null; do
    if ((elapsed >= timeout_seconds)); then
      log "ERROR: command timed out after ${timeout_seconds}s: $*"
      kill -TERM "$pid" 2>/dev/null || true
      for ((grace = 0; grace < 5; grace += 1)); do
        kill -0 "$pid" 2>/dev/null || break
        sleep 1
      done
      kill -KILL "$pid" 2>/dev/null || true
      wait "$pid" 2>/dev/null || true
      return 124
    fi
    ((elapsed == 0 || elapsed % HEARTBEAT_SECONDS == 0)) &&
      log "command still running (${elapsed}/${timeout_seconds}s): $*"
    sleep 1
    ((elapsed += 1))
  done
  if wait "$pid"; then
    return 0
  else
    return $?
  fi
}

status_is_stopped() {
  local status="$1" vm_name="$2" line
  if grep -Eiq 'running|suspend|paused' <<<"$status"; then
    return 1
  fi
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" =~ ^[[:space:]]*(State[[:space:]]*:[[:space:]]*)?stopped[[:space:]]*$ ]]; then
      return 0
    fi
    [[ "$line" == "VM $vm_name exist stopped" ]] && return 0
  done <<<"$status"
  return 1
}

vm_status() {
  prlctl status "$VM_NAME" 2>/dev/null || true
}

wait_for_stopped() {
  local attempt status
  for ((attempt = 1; attempt <= POLL_ATTEMPTS; attempt += 1)); do
    status="$(vm_status)"
    if status_is_stopped "$status" "$VM_NAME"; then
      return 0
    fi
    ((attempt == 1 || attempt % 5 == 0)) &&
      log "waiting for VM to stop (${attempt}/${POLL_ATTEMPTS})"
    sleep "$POLL_SECONDS"
  done
  return 1
}

stop_started_vm() {
  local stop_rc=0
  log "stopping VM"
  prlctl stop "$VM_NAME" >/dev/null 2>&1 || stop_rc=$?
  if ! wait_for_stopped; then
    log "ERROR: VM did not reach authoritative stopped state"
    return 1
  fi
  if ((stop_rc != 0)); then
    log "ERROR: prlctl stop failed (exit $stop_rc)"
    return "$stop_rc"
  fi
}

cleanup() {
  local rc=$?
  trap - EXIT INT TERM
  [[ -n "$SUBSET_MANIFEST" ]] && rm -f "$SUBSET_MANIFEST"
  if ((STARTED == 1)); then
    if stop_started_vm; then
      :
    else
      rc=$?
    fi
  fi
  exit "$rc"
}

trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

# The guest payload. It is quoted, so nothing here expands on the host; the
# manifest reaches the guest as base64 and the install functions mirror
# build-golden-image.sh's install_guest_tools.
guest_install_payload() {
  cat <<'INSTALL_SCRIPT'
set -Eeuo pipefail
export NONINTERACTIVE=1
export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"
manifest_path="$1"
tmp_dir="$(/usr/bin/mktemp -d "$HOME/.switchyard-cli.XXXXXX")"
trap '/bin/rm -rf "$tmp_dir"' EXIT

install_script_cli() {
  local provider="$1" url="$2" shell="$3" expected="$4" version="$5"
  local installer="$tmp_dir/$provider-installer"
  /usr/bin/curl --fail --silent --show-error --location --proto '=https' --tlsv1.2 \
    --output "$installer" "$url"
  printf '%s  %s\n' "$expected" "$installer" | /usr/bin/shasum -a 256 -c - >/dev/null
  /bin/chmod 700 "$installer"
  case "$provider" in
    claude) /bin/bash "$installer" "$version" >/dev/null ;;
    codex) CODEX_NON_INTERACTIVE=1 /bin/bash "$installer" --release "$version" >/dev/null ;;
    *)
      case "$shell" in
        bash) /bin/bash "$installer" >/dev/null ;;
        sh) /bin/sh "$installer" >/dev/null ;;
        *) printf '[guest] ERROR: invalid installer shell for %s\n' "$provider" >&2; exit 1 ;;
      esac
      ;;
  esac
}

install_npm_cli() {
  local provider="$1" package="$2" version="$3" expected="$4"
  local tarball
  npm config set prefix "$HOME/.local"
  tarball="$(npm pack --silent --pack-destination "$tmp_dir" "${package}@${version}" | /usr/bin/tail -n 1)"
  [[ "$tarball" != */* && -f "$tmp_dir/$tarball" ]] || {
    printf '[guest] ERROR: npm pack did not return a safe artifact for %s\n' "$provider" >&2
    exit 1
  }
  printf '%s  %s\n' "$expected" "$tmp_dir/$tarball" | /usr/bin/shasum -a 256 -c - >/dev/null
  if [[ "$package" == opencode-ai ]]; then
    npm install --global "$tmp_dir/$tarball" --allow-scripts=opencode-ai >/dev/null
  else
    npm install --global "$tmp_dir/$tarball" >/dev/null
  fi
}

# `brew install` is a no-op for an installed formula, so an existing install is
# upgraded instead. The version check below catches a formula that has moved
# away from the pinned release.
install_brew_cli() {
  local provider="$1" formula="$2" version="$3" expected="$4"
  local source="$tmp_dir/$provider-source" url
  url="$(/opt/homebrew/bin/brew info --json=v2 "$formula" | /usr/bin/python3 -c 'import json,sys; print(json.load(sys.stdin)["formulae"][0]["urls"]["stable"]["url"])')"
  /usr/bin/curl --fail --silent --show-error --location --proto '=https' --tlsv1.2 --output "$source" "$url"
  printf '%s  %s\n' "$expected" "$source" | /usr/bin/shasum -a 256 -c - >/dev/null
  if /opt/homebrew/bin/brew list --versions "$formula" >/dev/null 2>&1; then
    /opt/homebrew/bin/brew upgrade "$formula" >/dev/null || true
  else
    /opt/homebrew/bin/brew install "$formula" >/dev/null
  fi
}

extract_cli_version() {
  local raw="$1"
  printf '%s\n' "$raw" | awk '
    {
      for (i = 1; i <= NF; i++) {
        w = $i
        sub(/[^0-9A-Za-z]+$/, "", w)
        if (ver == "" && w ~ /^[0-9][0-9A-Za-z.+_-]*$/) {
          ver = w
        }
      }
    }
    END {
      if (ver != "") print ver
    }
  '
}

verify_cli_versions() {
  local manifest="$1"
  local provider kind ref detail expected version extra raw raw_first actual
  while IFS='|' read -r provider kind ref detail expected version extra; do
    [[ -z "${provider:-}" || "$provider" == \#* ]] && continue
    printf '[guest] verifying %s --version\n' "$provider" >&2
    command -v "$provider" >/dev/null 2>&1 || {
      printf '[guest] ERROR: pinned CLI is absent after installation: %s\n' "$provider" >&2
      exit 1
    }
    # stdin is the manifest; a CLI that reads it would silently skip later rows.
    raw="$("$provider" --version </dev/null 2>&1 || true)"
    raw_first="${raw%%$'\n'*}"
    actual="$(extract_cli_version "$raw")"
    if [[ -z "$actual" ]]; then
      printf '[guest] ERROR: %s reports no parseable version, manifest pins %s (raw: %s)\n' "$provider" "$version" "$raw_first" >&2
      exit 1
    fi
    if [[ "$actual" != "$version" ]]; then
      printf '[guest] ERROR: %s reports version %s, manifest pins %s (raw: %s)\n' "$provider" "$actual" "$version" "$raw_first" >&2
      exit 1
    fi
    printf '[guest] %s %s ok\n' "$provider" "$actual" >&2
  done <"$manifest"
}

# Reports the installed version token, or nothing when the CLI is absent.
installed_cli_version() {
  local provider="$1" raw
  command -v "$provider" >/dev/null 2>&1 || return 0
  raw="$("$provider" --version </dev/null 2>&1 || true)"
  extract_cli_version "$raw"
}

# Check each CLI first and install only the ones that differ from the pin.
while IFS='|' read -r provider kind ref detail expected version extra; do
  [[ -z "${provider:-}" || "$provider" == \#* ]] && continue
  current="$(installed_cli_version "$provider")"
  if [[ "$current" == "$version" ]]; then
    printf '[guest] %s %s already at the pinned version, skipping\n' "$provider" "$version" >&2
    continue
  fi
  printf '[guest] %s: installed %s, pinned %s; updating\n' "$provider" "${current:-none}" "$version" >&2
  case "$kind" in
    script) install_script_cli "$provider" "$ref" "$detail" "$expected" "$version" ;;
    npm) install_npm_cli "$provider" "$ref" "$detail" "$expected" ;;
    brew) install_brew_cli "$provider" "$ref" "$detail" "$expected" ;;
    *) printf '[guest] ERROR: unsupported pinned CLI kind: %s\n' "$kind" >&2; exit 1 ;;
  esac
done <"$manifest_path"

verify_cli_versions "$manifest_path"
INSTALL_SCRIPT
}

parse_args "$@"
require_host_tools
select_manifest_rows

log "checking VM is stopped"
initial_status="$(vm_status)"
status_is_stopped "$initial_status" "$VM_NAME" ||
  fail "VM must be stopped before update (observed: ${initial_status:-no status})"

if ((NO_SNAPSHOT == 0)); then
  SNAPSHOT_NAME="${SNAPSHOT_NAME:-pre-cli-update-$(date -u +%Y%m%dT%H%M%SZ)}"
  log "creating rollback snapshot $SNAPSHOT_NAME"
  prlctl snapshot "$VM_NAME" -n "$SNAPSHOT_NAME" -d "rollback point before update-guest-clis.sh" >/dev/null ||
    fail "could not create rollback snapshot (use --no-snapshot to skip)"
else
  log "skipping rollback snapshot (--no-snapshot)"
fi

log "starting VM"
STARTED=1
if prlctl start "$VM_NAME" >/dev/null; then
  :
else
  start_rc=$?
  log "ERROR: could not start VM (exit $start_rc)"
  exit "$start_rc"
fi

log "waiting for guest Tools"
guest_ready=0
for ((attempt = 1; attempt <= POLL_ATTEMPTS; attempt += 1)); do
  if run_bounded "$TOOLS_EXEC_TIMEOUT_SECONDS" prlctl exec "$VM_NAME" /bin/bash -lc ':'; then
    guest_ready=1
    log "guest Tools channel is ready"
    break
  fi
  ((attempt == 1 || attempt % 5 == 0)) &&
    log "waiting for guest Tools (${attempt}/${POLL_ATTEMPTS})"
  sleep "$POLL_SECONDS"
done
((guest_ready == 1)) || fail "guest Tools channel did not become ready"

# `prlctl exec` fails ("PrlJob_GetResult: Invalid argument") on stdin somewhere
# between 9 KB and 16 KB, so the payload, the manifest and the run step go over
# separate calls, each well under that.
readonly GUEST_MANIFEST='/tmp/switchyard-cli-manifest'
readonly GUEST_PAYLOAD='/tmp/switchyard-cli-install.sh'

guest_write_file() {
  local destination="$1"
  run_bounded "$TOOLS_EXEC_TIMEOUT_SECONDS" prlctl exec "$VM_NAME" /bin/bash -c \
    "umask 022; /bin/cat > '$destination'"
}

payload_bytes="$(guest_install_payload | wc -c | tr -d ' ')"
((payload_bytes < 8500)) || fail "guest payload is $payload_bytes bytes; split it (prlctl stdin limit)"
guest_install_payload | guest_write_file "$GUEST_PAYLOAD"
guest_write_file "$GUEST_MANIFEST" <"$SUBSET_MANIFEST"

log "updating $(wc -l <"$SUBSET_MANIFEST" | tr -d ' ') CLI(s) in the $PROVIDER_USER Aqua session"
run_bounded "$UPDATE_EXEC_TIMEOUT_SECONDS" prlctl exec "$VM_NAME" /bin/bash -c \
  "trap '/bin/rm -f $GUEST_MANIFEST $GUEST_PAYLOAD' EXIT; uid=\$(/usr/bin/id -u $PROVIDER_USER); /bin/launchctl asuser \$uid /usr/bin/sudo -iu $PROVIDER_USER /bin/bash $GUEST_PAYLOAD $GUEST_MANIFEST"

log "guest CLI update completed and verified"
